service:
  name: practice-server
  port: :19788
  host: host

mysql:
  host: host
  port: port
  username: username
  password: password
  database: database_name
  maxIdleConns: 10
  maxOpenConns: 100

redis:
  host: host
  port: port
  password:
  database: 0

rabbitmq:
  host: host
  port: port
  username: username
  password: password

grpc:
  host: host
  name: sql-practice

etcd:
  host: host
  port: 2379

